name: Generate ASCII Artwork

on: push

jobs:
    generate-ascii:
        runs on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5
            
            - name: Install cowsay program
              run: sudo apt-get install cowsay -y

            - name: Execute cowsay and save output
              run: |
                cowsay "Hello, GitHub Actions!" > ascii_art.txt
                cat ascii_art.txt

