name: Generate ASCII Artwork

on: push

jobs:
  build-job-1:
    runs-on: ubuntu-latest
    steps:   
      - name: Install cowsay program
        run: sudo apt-get install -y cowsay
      
      - name: Execute cowsay command
        run: cowsay "Hello, ASCII Art!" >> artwork.txt

      - name: upload artwork file
        uses: actions/upload-artifact@v4
        with:
          name: artwork-file
          path: artwork.txt
      
      - name: Sleep for 10 seconds
        run: sleep 10
  test-job-2:
    needs: build-job-1
    runs-on: ubuntu-latest
    steps:
      - name: Download artwork file
        uses: actions/download-artifact@v5
            
      - name: test file existence
        run: grep "ASCII" artwork.txt

  deploy-job-3:
    needs: [build-job-1, test-job-2]
    runs-on: ubuntu-latest
    steps:
      - name: Download artwork file
        uses: actions/download-artifact@v5

      - name: Display artwork
        run: cat artwork.txt