name: Generate ASCII Artwork

on: push

jobs:
    generate-ascii:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5
            
            - name: List files in the repository
              run: ls -ltra

            - name: Execute Shell script to generate ASCII artwork
              run: .github/workflows/ascii-script.sh

