name: Matrix Strategy Configuration

on: [push, workflow_dispatch]

jobs:
    deploy:
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                os: [ubuntu-latest, ubuntu-22.04.5, windows-latest]
                images: [hello-world, alpine]
                exclude:
                - os: windows-latest
                  images: alpine
                include:
                - os: ubuntu-22.04.5
                  images: busybox 
        runs-on: ${{ matrix.os }} 
        steps:
        - name: docker information
          run: docker info
            
        - name: Running image on ${{ matrix.os }}
          run: docker run ${{ matrix.images }}