name: Exploring Secrets and Variables

on: 
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes

env:
    container_registry: docker.io
    image_name: github-actions-nginx

jobs:
    docker-build:
        runs-on: ubuntu-latest

        steps:
            - name: docker build
              run: echo Building Docker image -t ${{ env.container_registry }}/${{vars.DOCKER_USERNAME}}/${{ env.image_name }}:latest
            
            - name: docker login
              run: echo Logging into Docker registry ${{ vars.DOCKER_USERNAME }}/${{ secrets.DOCKER_PASSWORD }}
            - name: docker push
              run:  echo Pushing Docker image ${{ env.container_registry }}/${{vars.DOCKER_USERNAME}}/${{ env.image_name }}:latest
    deploy:
        runs-on: ubuntu-latest
        needs: docker-build

        steps:
            - name: deploy
              run: echo Deploy application docker run -d -p 8080:80 ${{ env.container_registry }}/${{vars.DOCKER_USERNAME}}/${{ env.image_name }}:latest