name: Exploring Secrets and Variables

on: push

env:
    container_registry: docker.io
    image_name: github-actions-nginx

jobs:
    docker-build:
        runs-on: ubuntu-latest

        steps:
            - name: docker build
              run: |
                echo "Building Docker image..."
                docker build -t ${{ env.container_registry }}/${{vars.DOCKER_USERNAME}}/${{ env.image_name }}:latest .
            - name: docker login
              run: |
                echo "Logging into Docker registry..."
                echo ${{ vars.DOCKER_USERNAME }}/${{ secrets.DOCKER_PASSWORD }} | docker login ${{ env.container_registry }} -u ${{ vars.DOCKER_USERNAME }} --password-stdin
            - name: docker push
              run: |
                echo "Pushing Docker image..."
                docker push ${{ env.container_registry }}/${{vars.DOCKER_USERNAME}}/${{ env.image_name }}:latest
    deploy:
        runs-on: ubuntu-latest
        needs: docker-build

        steps:
            - name: deploy
              run: |
                echo "Deploy application..."
                docker run -d -p 8080:80 ${{ env.container_registry }}/${{vars.DOCKER_USERNAME}}/${{ env.image_name }}:latest